import type { Metadata } from "next";
import "./globals.css";
import { mainFont } from "./fonts/mainFonts";

export const metadata: Metadata = {
  title: "Sample TODO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${mainFont.className} antialiased`}>{children}</body>
    </html>
  );
}
